### ISSUE TITLE
[建议] 对ChatWeb的一些实用建议

### ISSUE THREAD

**Issue by Birditch** [FloraCore/ChatWeb#10]
1. <img width="961" alt="image" src="https://github.com/FloraCore/ChatWeb/assets/73741466/308cd38d-8045-4688-8a13-05f451676b2c">
如图，可以对前面第一部分进行颜色渲染以区分。
2. 每条消息点击复制该消息内容。

**Comment by Birditch** [comment]
@xLikeWATCHDOG ok

**Comment by SnowballXueQiu** [comment]
@xLikeWATCHDOG test

**Comment by SnowballXueQiu** [comment]
在[fdd37a8](https://github.com/FloraCore/ChatWeb/commit/fdd37a801fae81279cb43bc2e120c6470857bf6c)中已完成建议一

**Comment by Birditch** [comment]
@SnowballXueQiu 哦～谢谢哥！

**Comment by SnowballXueQiu** [comment]
@xLikeWATCHDOG 给你比个心

**Comment by Birditch** [comment]
@SnowballXueQiu 😘️️️️️️

**Comment by Birditch** [comment]
@xLikeWATCHDOG 🦞😘😒🤔😂👌😭😮👍😁😃😐🤣💨💨😔😔😄😄😳😜🙈😞😏😡😱😢🥲😇🍆🍎🍎🍊🍋🍋
