### ISSUE TITLE
[BUG] 右上角主题切换图标错误以及相应的BUG

### ISSUE THREAD

**Issue by Birditch** [FloraCore/ChatWeb#21]
<img width="64" alt="image" src="https://github.com/FloraCore/ChatWeb/assets/73741466/08ffd489-938d-4e67-8939-55cef72b8ef3">
如图所示，这个A应当放在右上角的。
并且当你点击A的时候，A会消失，但依然是暗黑主题。
如下图所示。
<img width="1624" alt="image" src="https://github.com/FloraCore/ChatWeb/assets/73741466/4ba7be5a-0344-43af-8c7d-156080f34e31">
只有点击了A外的部分，才会切换到白主题。

**Comment by SnowballXueQiu** [comment]
@xLikeWATCHDOG 好的，收到，在努力了

**Comment by Birditch** [comment]
现在相反了。
<img width="66" alt="image" src="https://github.com/FloraCore/ChatWeb/assets/73741466/686bdcf6-7584-4ad6-9b9d-d99f3fe4cc71">
白的时候点A的位置 会蹦出A。
<img width="66" alt="image" src="https://github.com/FloraCore/ChatWeb/assets/73741466/4fb064d1-4f4c-4cbc-86a2-8cf068e1e5e3">
