### ISSUE TITLE
[BUG] 导航栏样式错误

### ISSUE THREAD

**Issue by SnowballXueQiu** [FloraCore/ChatWeb#7]
- 在顶部导航栏中, 在其下层有一个不是很明显的白色矩形块, 但这并不正常, 具体效果如下如所示:
- ![导航栏问题](https://s2.loli.net/2023/08/29/6CQNY8Kf35WRkHg.png)
---
- 我在DevTool中尝试删除这个div元素, 但删除后整个头部导航栏就只剩下一个白底了.
- 在DevTool中的代码片段如图所示(已删除svg标签):
- ![html](https://s2.loli.net/2023/08/29/hmyBs5HckxDLKZU.png)

**Comment by GaoNeng-wWw** [comment]
![Snipaste_2023-08-29_10-04-53](https://github.com/FloraCore/ChatWeb/assets/31283122/b97744ba-2be9-4ffb-a02d-33120bf4759d)
不算做bug，因为menu在右边，menu有border-bottom但logo没有，给你的错觉

**Comment by xLikeWATCHDOG** [comment]
测试一下

**Comment by xLikeWATCHDOG** [comment]
测试
